"""Auto-generated model card.

Builds a deterministic Markdown model card from the persistent store. The card
summarises the most recent runs, top alerts, calibration headlines, baselines,
and the audit trail. The output is intentionally Markdown so it can be (a)
attached to a PR, (b) handed to the QMS team verbatim, or (c) rendered
elsewhere.
"""

from __future__ import annotations

from datetime import datetime, timezone

from biomodel_monitor import __version__
from biomodel_monitor.store.repository import MetricsStore


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.strip()}\n"


def build_model_card(
    store: MetricsStore,
    *,
    model_id: str,
    model_version: str,
    last_n_runs: int = 10,
) -> str:
    """Return a Markdown model card string."""
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    runs = store.list_runs(
        model_id=model_id, model_version=model_version, limit=last_n_runs,
    )
    alerts = store.list_alerts(
        model_id=model_id, model_version=model_version, limit=200,
    )
    baselines = store.list_baselines(
        model_id=model_id, model_version=model_version,
    )
    annotations = store.list_annotations(
        model_id=model_id, model_version=model_version,
    )

    parts: list[str] = [
        f"# Model Card — `{model_id}` @ `{model_version}`\n",
        f"_Generated by BioModel Monitor v{__version__} at {now}_\n",
    ]

    # Overview
    n_alerts_total = sum(r.n_alerts for r in runs)
    overview = (
        f"- Runs (last {last_n_runs}): **{len(runs)}**\n"
        f"- Alerts emitted across those runs: **{n_alerts_total}**\n"
        f"- Distinct alert keys observed: **{len({a.key for a in alerts})}**\n"
        f"- Baselines on file: **{len(baselines)}** "
        f"(promoted: {sum(1 for b in baselines if b.get('status') == 'promoted')})\n"
    )
    parts.append(_section("Overview", overview))

    # Recent runs
    if runs:
        rows = ["| Run ID | Batch | Started | Alerts |", "|---|---|---|---|"]
        for r in runs[:last_n_runs]:
            rows.append(
                f"| `{r.run_id[:8]}…` | `{r.batch_id}` | {r.started_at} | {r.n_alerts} |"
            )
        parts.append(_section("Recent runs", "\n".join(rows)))

    # Top recurring alerts
    by_key: dict[str, dict] = {}
    for a in alerts:
        bk = by_key.setdefault(a.key, {
            "title": a.title, "category": a.category, "severity": a.severity,
            "n": 0, "max_persistence": 0,
        })
        bk["n"] += 1
        bk["max_persistence"] = max(bk["max_persistence"], a.persistence)
        # escalate stored severity
        rank = {"ok": 0, "warn": 1, "alert": 2}
        if rank.get(a.severity, 0) > rank.get(bk["severity"], 0):
            bk["severity"] = a.severity
    if by_key:
        ranked = sorted(by_key.items(), key=lambda kv: (-kv[1]["max_persistence"], -kv[1]["n"]))[:10]
        rows = ["| Key | Title | Severity | Category | Occurrences | Max persistence |",
                "|---|---|---|---|---|---|"]
        for key, info in ranked:
            rows.append(
                f"| `{key}` | {info['title']} | {info['severity']} | "
                f"{info['category']} | {info['n']} | {info['max_persistence']} |"
            )
        parts.append(_section("Top recurring alerts", "\n".join(rows)))

    # Audit trail
    if annotations:
        rows = ["| Time | Alert | Kind | Label | Actor | Note |",
                "|---|---|---|---|---|---|"]
        for a in annotations[-20:]:
            rows.append(
                f"| {a.created_at} | `{a.alert_key}` | {a.kind} | "
                f"{a.label or '-'} | {a.actor or '-'} | "
                f"{(a.note or '').replace('|', '/')[:80]} |"
            )
        parts.append(_section("Audit trail (last 20)", "\n".join(rows)))

    # Baselines
    if baselines:
        rows = ["| ID | Status | Cohort | Site | n | Created | Promoted |",
                "|---|---|---|---|---|---|---|"]
        for b in baselines[:20]:
            rows.append(
                f"| {b['id']} | {b['status']} | {b.get('cohort') or '-'} | "
                f"{b.get('site_id') or '-'} | {b.get('n', 0)} | {b['created_at']} | "
                f"{b.get('promoted_at') or '-'} |"
            )
        parts.append(_section("Baselines", "\n".join(rows)))

    parts.append(
        _section(
            "Disclaimer",
            "This card is auto-generated from monitoring telemetry. It is **not** a "
            "substitute for a clinical-grade model card or a QMS document; treat it "
            "as an evidence pack to support those processes.",
        )
    )
    return "\n".join(parts)


__all__ = ["build_model_card"]
